export class LetterText {

  public static text: string = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pharetra dui vitae nisl aliquam sodales. Aliquam fermentum accumsan nisl, eget sollicitudin odio eleifend eget. Pellentesque sit amet metus a nibh luctus pellentesque nec non felis. Vestibulum auctor pulvinar lacus eu tristique. Nullam sit amet quam augue. In gravida, libero id aliquam congue, nunc ligula gravida urna, id tincidunt lacus metus sed tellus. Integer lobortis malesuada diam, in tincidunt justo feugiat vitae. Fusce diam massa, mollis in auctor ut, posuere quis neque. Phasellus ultricies felis in porttitor congue. Maecenas vestibulum faucibus neque in fermentum. Maecenas id tempus ante. Proin mattis dignissim felis non accumsan. Maecenas nec diam dictum, semper sapien dictum, accumsan est. Nam vitae lacus maximus, elementum enim sed, convallis odio. In id ligula sit amet magna eleifend accumsan.\n' +
    '\n' +
    'Curabitur velit quam, euismod sed tellus sed, sollicitudin mattis orci. Morbi non neque nulla. Morbi tristique leo non ex ornare, a lobortis purus pretium. Nunc tempus, elit at porttitor faucibus, arcu felis malesuada mauris, sodales ornare sapien arcu quis magna. Duis in volutpat ante. Donec semper dui a metus lacinia, id lobortis lectus pellentesque. Nam fermentum mollis elit nec molestie. Fusce quam ipsum, malesuada sed leo non, pretium viverra purus. Pellentesque ut condimentum nulla. Donec malesuada mi tellus, ut hendrerit dui commodo vel. Pellentesque eleifend felis vel malesuada ultrices.\n' +
    '\n' +
    'Ut eleifend volutpat mauris, non hendrerit odio egestas quis. Praesent rhoncus, ipsum vel blandit tempus, sapien ipsum convallis turpis, in condimentum mauris tortor id eros. Phasellus et augue pretium, dictum ex consequat, finibus ante. Morbi pharetra, nisl eu ornare accumsan, ex odio fermentum est, vel dignissim est nisl ut turpis. Praesent porta vehicula mauris eget malesuada. Ut at ante non metus fermentum congue. Curabitur dictum orci lacus, eu posuere eros bibendum et. Donec est augue, mollis vitae nibh vel, porttitor vehicula odio.\n' +
    '\n' +
    'Sed mauris ligula, euismod eu erat sit amet, consequat accumsan lectus. Donec rhoncus vitae odio sed bibendum. Quisque pulvinar rhoncus odio, et accumsan purus sodales eget. Fusce feugiat augue ornare dui viverra sollicitudin. Donec eu congue turpis. Quisque dapibus libero lacus, in finibus nisi consectetur sed. Etiam efficitur mauris nec ex cursus volutpat et a metus. Integer vel ornare velit. Sed iaculis dignissim nulla sit amet interdum. Nunc non leo urna.\n' +
    '\n' +
    'Pellentesque ullamcorper enim est, in congue elit hendrerit sit amet. Aliquam ut consequat augue. Suspendisse potenti. Nulla fringilla id risus eget iaculis. Integer vitae tempor est. Integer id libero mattis, rhoncus urna eget, blandit tellus. In finibus eget erat vitae molestie. Integer dictum, odio ut posuere rutrum, nulla neque elementum velit, sit amet gravida mi ex ut velit. Nunc non tellus tincidunt, luctus justo quis, viverra massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam porta volutpat urna nec rhoncus. Nullam eget metus massa.';

}

